version: "3.8"

services:
  web:
    build:
      context: .
    container_name: studyhub-web
    restart: always
    command: >
      bash -c "python manage.py migrate && python manage.py collectstatic --noinput && exec uwsgi --ini /app/uwsgi.ini"
    volumes:
      - static_volume:/app/static
      - uwsgi_sock:/app/uwsgi.sock
    ports:
      - "3031:3031"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3031 || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:latest
    container_name: studyhub-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/static
      - uwsgi_sock:/app/uwsgi.sock
    depends_on:
      - web

volumes:
  static_volume:
  uwsgi_sock:
    driver: local
